"""Initial

Revision ID: 539f9b3f70c3
Revises: 
Create Date: 2022-12-20 07:40:49.562924

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '539f9b3f70c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
