version: '3.7'

services:
  db-test:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TESTING=True
    env_file:
      - ./.env
    ports:
      - 5432:5432

  frames-test:
    build:
      context: ../frames
      dockerfile: Dockerfile
    command: 
      bash -c "pytest"
    restart: always
    volumes:
      - ../frames/:/frames
      - ../frames/static/:/frames/static
    environment:
      - TESTING=True
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db-test

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  frames:
    build:
      context: ../frames
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0
    restart: always
    volumes:
      - ../frames/:/frames
      - ../frames/static/:/frames/static
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db


volumes:
  postgres_data: